### PR TITLE
Proposal for hosting the MLH Local Hack Day at Oakton High School

### PR DESCRIPTION
**Pull request by ApolloZhu**
I confirm that:

- [x] I have read and understand [the process document](https://github.com/oaktoncsclub/club-evolution/blob/master/process.md).
- [x] I used [the template file](https://github.com/oaktoncsclub/club-evolution/blob/master/0000-template.md) for this proposal.

First hackathon by Oakton Computer Science Club! @dgramop 

We'll definitely need to email Mr. Lau for approval, but let's first vote on this ourselves (react with thumbs up or down). Amendments are welcome.

### CODE REVIEW

**Comment by treblotmail** [comment]
This seems really cool. I would say go for it if you haven't already :)

**Comment by DestinyFate** [comment]
I think this would work out. But it needs a lot of planning... tons of sponsors. TJ went successful because it is TJ. It pulls in students and companies, but Oakton... hmmmm.....

**Comment by dgramop** [comment]
YES!! This would be really dank

**Comment by ApolloZhu** [comment]
@treblotmail Actually this is a set date by MLH, and the next week (Dec. 9th) we have Virginia Tech High School Programming Contest...

**Comment by ApolloZhu** [comment]
By the way Mr. Lau just approved the idea, but requested more details to be finalized. @dgramop Do you mind [email the MLH](mailto:localhackday@mlh.io?subject=MLH%20Local%20Hack%20Day%20Questions) for clarification about

> the detailed itinerary, to what extent will they sponsor us? Snacks/Lunch/Dinner? Drinks? Money? What kind of workshop materials? Maybe guest speakers? How are we required to show their sponsors' ads?

and any other concerns you have?

**Comment by ApolloZhu** [comment]
image

**Pull request closed without merging**
